#没有匹配的展示
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev #开发模式
  application:
    name: microservicecloud-config-eureka

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

      #不注册自己信息
      defaultZone: http://eureka7004.com:7004/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
spring:
  profiles: test #测试模式
  application:
    name: microservicecloud-config-eureka

server:
  port: 7001

eureka:
  instance:
    hostname: eureka-test7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

      #不注册自己信息
      defaultZone: http://eureka7004.com:7004/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---

spring:
  profiles: test #测试模式
  application:
    name: microservicecloud-config-client

server:
  port: 8202

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-test7001.com:7001/eureka
#请保存为UTF-8 格式
